version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: "chore(deps): "
      prefix-development: "chore(dev_deps): "
      include: "scope"
