name: 'Setup Deno'
description: 'GitHub Actions to set up Deno'
author: 'Maximous Black'
branding:
  icon: 'package'
  color: 'gray-dark'
inputs:
  version:
    description: 'Deno version'
    default: 'latest'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
