name: 'UN1QE Action'
description: 'Action description'
author: 'Maximous Black'
branding:
  icon: 'box'
  color: 'gray-dark'
inputs:
  milliseconds:
    required: true
    description: 'time in millisecons'
    default: '50'
runs:
  using: 'node12'
  main: 'dist/index.js'
