name: 'Setup Deno'
description: 'GitHub Actions to install and set up Deno'
author: 'Maximous Black'
branding:
  icon: 'box'
  color: 'gray-dark'
inputs:
  version:
    description: 'Deno version'
    default: "v1.x"
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
