name: Build

on:
  pull_request:
  push:

jobs:
  pkg:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Package
        run: yarn pkg

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        deno: ['v1.x', '1', 'v1.7.1', 'v1', 'canary', 'v404']

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Run action
        uses: ./
        with:
          version: ${{ matrix.deno }}

      - name: Run Deno
        run: deno --version
