name: Ship

on:
  release:
    types: [published]

  workflow_dispatch:
    inputs:
      tag:
        description: Semver tag
        required: true

jobs:
  build:
    if: github.event.inputs
    runs-on: ubuntu-latest
    timeout-minutes: 20

    outputs:
      commit: ${{ steps.commit.outputs.hash }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: Install Dependencies
        run: yarn install

      - name: Build
        run: yarn dist

      - name: Commit Build
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'build: ${{ github.repository }}@v${{ github.event.inputs.tag }}'
          file_pattern: 'dist/*'

      - name: Get Commit
        id: commit
        run: echo "::set-output name=hash::$(git rev-parse HEAD)"

  release:
    if: github.event.inputs
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: maximousblk/setup-deno@main
        with:
          deno-version: v1.11.2

      - name: Generate Release Notes
        run: deno run -A https://deno.land/x/ghlog/ghlog.ts ${{ github.repository }} -v '${{ github.event.inputs.tag }}'

      - name: Release v${{ github.event.inputs.tag }}
        uses: ncipollo/release-action@v1
        with:
          commit: '${{ needs.build.outputs.commit }}'
          tag: 'v${{ github.event.inputs.tag }}'
          name: 'v${{ github.event.inputs.tag }}'
          bodyFile: 'CHANGELOG.md'
          draft: true
          token: ${{ github.token }}

  tag:
    runs-on: ubuntu-latest
    if: github.event.action == 'published'

    env:
      GITHUB_TOKEN: '${{ github.token }}'

    steps:
      - name: Update convenience tags
        uses: Actions-R-Us/actions-tagger@latest
        with:
          publish_latest_tag: true
