name: Tags

on:
  release:
    types: [published]

jobs:
  update:
    runs-on: windows-latest
    steps:
      - name: Update convenience tags
        uses: Actions-R-Us/actions-tagger@latest
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        with:
          publish_latest_tag: true
