name: Test

on:
  pull_request:
  push:

jobs:
  test:
    name: test / ${{ matrix.os }} / ${{ matrix.deno }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        deno: ['v1.x', '1', 'v1.7.1', 'v1', 'canary', 'v404']
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Run action
        uses: ./
        with:
          version: ${{ matrix.deno }}

      - name: Run Deno
        run: deno --version
