name: Test

on:
  pull_request:
  push:

jobs:
  run:
    name: run / ${{ matrix.deno }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        deno: ['v1.7.1', 'v1.6.x', 'v1', '1', 'latest', 'canary']

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Run action
        uses: ./
        with:
          version: ${{ matrix.deno }}

      - name: Run Deno
        run: deno --version
