name: Test

on:
  pull_request:
  push:

jobs:
  test:
    name: test / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: Install dependencies
        run: yarn install

      - name: Run Tests
        run: yarn test

  run:
    name: run / ${{ matrix.deno }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        deno: ['1', '1.11', '1.11.2', 'latest', '4e3ec478573ede7247fd306cad1ea5bf2d5c9565', 'canary']
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Run action
        uses: ./
        with:
          version: ${{ matrix.deno }}

      - name: Deno version
        run: deno --version

      - name: Deno info
        run: deno info

      - name: Deno path
        run: whereis deno

      - name: Deno Install
        run: |
          deno install --allow-net -n deno_curl https://deno.land/std/examples/curl.ts
          deno_curl https://deno.land/std/examples/curl.ts
