name: Test

on:
  pull_request:
  push:

jobs:
  run:
    name: run / ${{ matrix.deno }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        deno: ['v1.7.0', 'v1.7.x', '1.x', '1', 'latest', 'canary']

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Run action
        uses: ./
        with:
          version: ${{ matrix.deno }}

      - name: Deno version
        run: deno --version

      - name: Deno info
        run: deno info

      - name: Deno path
        run: |
          ${{ runner.os == 'Windows' && ' Set-Alias whereis where.exe' || ''}}
          whereis deno
